#if !canImport(ObjectiveC)
import XCTest

extension IndexStoreDBTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__IndexStoreDBTests = [
        ("testErrors", testErrors),
    ]
}

extension LocationScannerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__LocationScannerTests = [
        ("testDirectory", testDirectory),
        ("testDuplicate", testDuplicate),
        ("testLocation", testLocation),
        ("testMultiple", testMultiple),
        ("testName", testName),
        ("testNested", testNested),
        ("testSmall", testSmall),
    ]
}

extension TibsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TibsTests = [
        ("testBasic", testBasic),
        ("testMixedLangTarget", testMixedLangTarget),
        ("testSwiftModules", testSwiftModules),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(IndexStoreDBTests.__allTests__IndexStoreDBTests),
        testCase(LocationScannerTests.__allTests__LocationScannerTests),
        testCase(TibsTests.__allTests__TibsTests),
    ]
}
#endif
